admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

service:
  type: NodePort
  port: 3000

persistence:
  enabled: true
  size: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce

initChownData:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

env:
  GF_SMTP_ENABLED: true
  GF_SMTP_HOST: smtp.gmail.com:587
  GF_SMTP_STARTTLS: true
  # These will be filled by Helm via --set from Jenkins
  GF_SMTP_USER: "{{ .Values.smtp.user }}"
  GF_SMTP_PASSWORD: "{{ .Values.smtp.password }}"
  GF_SMTP_FROM_ADDRESS: "{{ .Values.smtp.from }}"
  GF_SMTP_FROM_NAME: "Grafana Notifier"
  GF_SMTP_SKIP_VERIFY: true
  GF_ALERTING_ENABLED: true
  GF_ALERTING_CONTACTPOINTS_FILE: /etc/grafana/notifiers/smtp-contact.yaml
  GF_ALERTING_RULES_FILE: /etc/grafana/alerts/cpu-ram-alerts.yaml

extraVolumeMounts:
  - name: notifiers
    mountPath: /etc/grafana/notifiers
  - name: alerts
    mountPath: /etc/grafana/alerts

extraVolumes:
  - name: notifiers
    configMap:
      name: grafana-contact
  - name: alerts
    configMap:
      name: grafana-alerts
