{
 "title": "Task dashboard",
 "description": "RS School AWS DevOps course Task-7",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "description": "CPU usage (All cluster)",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory usage (%)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (GB)",
   "type": "bargauge",
   "description": "Memory usage (GB)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Disk usage (%)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (sum(node_filesystem_avail_bytes{fstype=~\"ext4|xfs\"}) / sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "description": "Disk usage",
   "gridPos": { "h": 6, "w": 12, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) - sum(node_filesystem_avail_bytes{fstype=~\"ext4|xfs\"}))/1024/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage (GB)",
   "type": "bargauge",
   "description": "Disk usage (GB)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"}) - sum(node_filesystem_avail_bytes{fstype=~\"ext4|xfs\"}))/1024/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}