apiVersion: v2
name: jenkins-deployment
description: A Helm chart for Jenkins with JCasC configuration
type: application
version: 0.1.0
appVersion: "2.504.3"
dependencies:
  - name: jenkins
    version: "5.7.15"
    repository: "https://charts.jenkins.io"