jenkins:
  controller:
    image:
      registry: docker.io
      repository: evgeneys/jenkins-with-tools
      tag: latest
      pullPolicy: Always
      # pullPolicy: IfNotPresent
    
    initContainerEnv:
      - name: DISABLE_INIT_CONTAINER
        value: "true"

    initContainers: []

    sidecars:
      configAutoReload:
        enabled: false

    imagePullPolicy: IfNotPresent

    JCasC:
      defaultConfig: true
      configScripts:
        security: |
          jenkins:
            securityRealm:
              local:
                allowsSignup: false
                users:
                  - id: "admin"
                    password: "admin123"
            authorizationStrategy:
              loggedInUsersCanDoAnything:
                allowAnonymousRead: false
        jobs: |
          jobs:
            - script: >
                freeStyleJob('hello-world') {
                  description('Hello World job created via JCasC')
                  steps {
                    shell('echo "Hello world"')
                  }
                }
    persistence:
      enabled: true
      size: 8Gi
    additionalPlugins:
      - job-dsl:1.87
