apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-contact
data:
  contact-points.yaml: |-
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: "admin-email-contact"
        receivers:
          - uid: "admin-email1"
            type: "email"
            settings:
              addresses: {{ .Values.contact.to | quote }}
