apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: provisioning
    app.kubernetes.io/part-of: monitoring
    managed-by: Helm
data:
  alerts.yaml: |-
    apiVersion: 1
    groups:
      - name: resource-alerts
        folder: Cluster Alerts
        interval: 1m
        rules:
          - uid: high-cpu-usage
            title: High CPU usage
            condition: C
            data:
              - refId: A
                queryType: ""
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: prometheus-server
                model:
                  expr: sum(rate(container_cpu_usage_seconds_total{image!=""}[2m])) by (node)
                  format: time_series
                  interval: ""
                  intervalFactor: 2
                  legendFormat: "{{`{{ node }}`}}"
                  refId: A
              - refId: B
                queryType: ""
                relativeTimeRange:
                  from: 0
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - B
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  hide: false
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: last
                  refId: B
                  type: reduce
              - refId: C
                queryType: ""
                relativeTimeRange:
                  from: 0
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - {{ .Values.alerts.cpuThreshold | default 0.75 }}
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: $B > {{ .Values.alerts.cpuThreshold | default 0.75 }}
                  hide: false
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: math
            for: 1m
            noDataState: NoData
            execErrState: Alerting
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above {{ mul (.Values.alerts.cpuThreshold | default 0.75) 100 }}% for more than 1 minute"
            labels:
              severity: warning

          - uid: low-mem-available
            title: Low available memory
            condition: C
            data:
              - refId: A
                queryType: ""
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: prometheus-server
                model:
                  expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)
                  format: time_series
                  interval: ""
                  intervalFactor: 2
                  legendFormat: "{{`{{ instance }}`}}"
                  refId: A
              - refId: B
                queryType: ""
                relativeTimeRange:
                  from: 0
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - B
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  hide: false
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: last
                  refId: B
                  type: reduce
              - refId: C
                queryType: ""
                relativeTimeRange:
                  from: 0
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - {{ .Values.alerts.memThreshold | default 0.25 }}
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: $B < {{ .Values.alerts.memThreshold | default 0.25 }}
                  hide: false
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: C
                  type: math
            for: 1m
            noDataState: NoData
            execErrState: Alerting
            annotations:
              summary: "Low available memory detected"
              description: "Less than {{ mul (.Values.alerts.memThreshold | default 0.25) 100 }}% RAM is available"
            labels:
              severity: warning
  contact-points.yaml: |-
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: "admin-email-contact"
        receivers:
          - uid: "admin-email1"
            type: "email"
            settings:
              addresses: {{ .Values.contact.to | quote }}
  policies.yaml: |-
    apiVersion: 1
    policies:
      - orgId: 1
        receiver: "admin-email-contact"
        group_by: ['alertname']
        matchers: []
        continue: false
